version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: edugen-postgres
    environment:
      POSTGRES_DB: edugen
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - edugen-network

  backend:
    build: ./backend
    container_name: edugen-backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/edugen
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "8080:8080"
    networks:
      - edugen-network

  frontend:
    build: ./frontend
    container_name: edugen-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - edugen-network

networks:
  edugen-network:
    driver: bridge

volumes:
  postgres-data: